spring.application.name=PaymentService
server.port=9012
spring.config.import=configserver:http://localhost:8888
eureka.client.service-url.default= http://localhost:8761/eureka
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG
spring.kafka.bootstrap-servers=pkc-921jm.us-east-2.aws.confluent.cloud:9093

spring.kafka.producer.properties.security.protocol=SASL_SSL
spring.kafka.producer.properties.sasl.mechanism=PLAIN

spring.kafka.producer.properties.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="5ARFPJTHRHS2MX2E" password="cfltaYFZsyMWg6iXbFT7Y/o6o9ReR7CR2iv6lU5CNsvVhn0th3aMs4bRNEDi6DRg";

spring.kafka.producer.properties.ssl.endpoint.identification.algorithm=https
logging.level.org.apache.kafka=DEBUG
logging.level.org.springframework.kafka=DEBUG