spring.application.name=PaymentService
server.port=9015
spring.config.import=configserver:http://localhost:8888
eureka.client.service-url.default= http://localhost:8761/eureka
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG
spring.kafka.bootstrap-servers=pkc-921jm.us-east-2.aws.confluent.cloud:9093

spring.cache.type=redis
java.net.preferIPv4Stack=true

spring.data.redis.host=redis-10024.c245.us-east-1-3.ec2.cloud.redislabs.com
spring.data.redis.port=10024
spring.data.redis.username=default
spring.data.redis.password=QPrS5VwZ13HyiQY0bQ704QtpUhkkJGo5
spring.data.redis.ssl.enabled=false

spring.redis.timeout=60000
spring.redis.lettuce.pool.max-active=10
spring.redis.lettuce.pool.max-idle=5
spring.redis.lettuce.pool.min-idle=1

services.fraud-url:http://localhost:9016